const logs = [
  {name:'Berlin', initials:'B', date:'15 Sep 2026', entry:'09:12', exit:'—', status:'On site', type:'present'},
  {name:'Nairobi', initials:'N', date:'15 Sep 2026', entry:'08:43', exit:'09:04', status:'Completed', type:'closed'},
  {name:'Denver', initials:'D', date:'15 Sep 2026', entry:'08:58', exit:'—', status:'On site', type:'present'},
  {name:'Rio', initials:'R', date:'15 Sep 2026', entry:'09:21', exit:'—', status:'Late', type:'late'},
  {name:'Helsinki', initials:'H', date:'15 Sep 2026', entry:'08:35', exit:'—', status:'On site', type:'present'},
  {name:'Lisbon', initials:'L', date:'15 Sep 2026', entry:'08:41', exit:'—', status:'On site', type:'present'}
];
let stream, onsite = 24, present = 36, pending = 6;
const $ = id => document.getElementById(id);
const timeString = d => d.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});
function updateClock(){const now=new Date();$('liveTime').textContent=now.toLocaleTimeString('en-GB');$('liveDate').textContent=now.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}).toUpperCase()} updateClock();setInterval(updateClock,1000);
function renderLogs(items=logs){$('logBody').innerHTML=items.map(l=>`<tr><td><div class="operative"><span class="table-avatar">${l.initials}</span>${l.name}</div></td><td>${l.date}</td><td>${l.entry}</td><td>${l.exit}</td><td><span class="status ${l.type}">${l.status}</span></td></tr>`).join('')}
renderLogs();
function updateCounters(){ $('onsiteCount').textContent=String(onsite).padStart(2,'0');$('presentCount').textContent=String(present).padStart(2,'0');$('pendingCount').textContent=String(pending).padStart(2,'0');$('presentKey').textContent=present;$('pendingKey').textContent=String(pending).padStart(2,'0');const pct=Math.round(present/(present+pending)*100);$('ringPercentage').textContent=pct+'%';document.querySelector('.ring').style.background=`radial-gradient(closest-side,var(--panel) 77%,transparent 78% 100%),conic-gradient(var(--red) ${pct}%,${document.body.classList.contains('light')?'#d0cfcb':'#3a3a3c'} 0)`;}
async function enableCamera(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});$('camera').srcObject=stream;$('camera').style.display='block';$('cameraPlaceholder').style.display='none';$('startCamera').textContent='Camera active';$('startCamera').disabled=true;$('scanResult').textContent='BIOMETRIC CHANNEL READY'}catch(e){$('scanResult').textContent='CAMERA UNAVAILABLE — DEMO MODE ENABLED';showToast('Demo mode active','You can still mark attendance manually.')}}
$('startCamera').addEventListener('click',enableCamera);
function showToast(title,text){$('toastTitle').textContent=title;$('toastText').textContent=text;$('toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3800)}
$('closeToast').onclick=()=>$('toast').classList.remove('show');
function mark(kind){const field=$('employeeName'),name=field.value.trim();if(!name){field.focus();showToast('Identity required','Enter an operative name before scanning.');return}const now=new Date(),time=timeString(now),date=now.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});let record=logs.find(x=>x.name.toLowerCase()===name.toLowerCase()&&x.date===date&&x.exit==='—');if(kind==='entry'){if(record){showToast('Already on site',`${name} checked in at ${record.entry}.`);return}logs.unshift({name,initials:name.slice(0,1).toUpperCase(),date,entry:time,exit:'—',status:'On site',type:'present'});onsite++;present++;pending=Math.max(0,pending-1);activity(name,'Entered the premises',time)}else{if(record){record.exit=time;record.status='Completed';record.type='closed';onsite=Math.max(0,onsite-1)}else{logs.unshift({name,initials:name.slice(0,1).toUpperCase(),date,entry:'—',exit:time,status:'Completed',type:'closed'});}activity(name,'Checked out',time)}$('scanResult').textContent=`MATCH CONFIRMED — ${name.toUpperCase()}`;renderLogs();updateCounters();showToast(kind==='entry'?'Entry recorded':'Exit recorded',`${name} — ${time} has been stored in the log.`)}
function activity(name,action,time){const li=document.createElement('li');li.innerHTML=`<span class="mini-avatar red-avatar">${name[0].toUpperCase()}</span><div><b>${name}</b><small>${action}</small></div><time>${time}</time>`;$('activityList').prepend(li);if($('activityList').children.length>3)$('activityList').lastElementChild.remove()}
$('entryBtn').onclick=()=>mark('entry');$('exitBtn').onclick=()=>mark('exit');
$('searchInput').addEventListener('input',e=>renderLogs(logs.filter(x=>x.name.toLowerCase().includes(e.target.value.toLowerCase()))));
$('themeToggle').onclick=()=>{document.body.classList.toggle('light');updateCounters()};
$('exportBtn').onclick=()=>{const rows=[['Operative','Date','Entry','Exit','Status'],...logs.map(x=>[x.name,x.date,x.entry,x.exit,x.status])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='la-casa-attendance-'+new Date().toISOString().slice(0,10)+'.csv';a.click();URL.revokeObjectURL(a.href);showToast('Archive exported','Your attendance CSV is ready.');};
